# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - mycelium-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r flask/requirements.txt

      - name: Install Ultralytics separately (no dependencies)
        run: |
          source venv/bin/activate
          pip install ultralytics --no-deps

      - name: Install test dependencies
        run: |
          source venv/bin/activate
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          source venv/bin/activate
          cd flask
          python -m pytest tests/ -v --tb=short --maxfail=5
        env:
          PYTHONPATH: .

  build:
    runs-on: ubuntu-latest
    needs: test  # Build only runs if tests pass
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r flask/requirements.txt

      - name: Install Ultralytics separately (no dependencies)
        run: |
          source venv/bin/activate
          pip install ultralytics --no-deps

      - name: Zip artifact for deployment
        run: cd flask && zip -r ../release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]  # Deploy only runs if both test and build pass
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "mycelium-api"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_516EA5E09DAA4F8CADAA042B38542BEC }}